// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: deployment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentStatus int32

const (
	DeploymentStatus_DEPLOYMENT_STATUS_UNSPECIFIED DeploymentStatus = 0
	DeploymentStatus_DEPLOYMENT_STATUS_PENDING     DeploymentStatus = 1
	DeploymentStatus_DEPLOYMENT_STATUS_RUNNING     DeploymentStatus = 2
	DeploymentStatus_DEPLOYMENT_STATUS_STOPPED     DeploymentStatus = 3
	DeploymentStatus_DEPLOYMENT_STATUS_FAILED      DeploymentStatus = 4
	DeploymentStatus_DEPLOYMENT_STATUS_RESTARTING  DeploymentStatus = 5
)

// Enum value maps for DeploymentStatus.
var (
	DeploymentStatus_name = map[int32]string{
		0: "DEPLOYMENT_STATUS_UNSPECIFIED",
		1: "DEPLOYMENT_STATUS_PENDING",
		2: "DEPLOYMENT_STATUS_RUNNING",
		3: "DEPLOYMENT_STATUS_STOPPED",
		4: "DEPLOYMENT_STATUS_FAILED",
		5: "DEPLOYMENT_STATUS_RESTARTING",
	}
	DeploymentStatus_value = map[string]int32{
		"DEPLOYMENT_STATUS_UNSPECIFIED": 0,
		"DEPLOYMENT_STATUS_PENDING":     1,
		"DEPLOYMENT_STATUS_RUNNING":     2,
		"DEPLOYMENT_STATUS_STOPPED":     3,
		"DEPLOYMENT_STATUS_FAILED":      4,
		"DEPLOYMENT_STATUS_RESTARTING":  5,
	}
)

func (x DeploymentStatus) Enum() *DeploymentStatus {
	p := new(DeploymentStatus)
	*p = x
	return p
}

func (x DeploymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_deployment_proto_enumTypes[0].Descriptor()
}

func (DeploymentStatus) Type() protoreflect.EnumType {
	return &file_deployment_proto_enumTypes[0]
}

func (x DeploymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStatus.Descriptor instead.
func (DeploymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{0}
}

type DeploymentSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ImageTag      string                 `protobuf:"bytes,3,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                                                                               // Container internal port
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`                                                                                            // Subdomain for routing
	EnvVars       map[string]string      `protobuf:"bytes,6,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	Secrets       map[string]string      `protobuf:"bytes,7,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                // Decrypted secrets
	Resources     *ResourceLimits        `protobuf:"bytes,8,opt,name=resources,proto3" json:"resources,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentSpec) Reset() {
	*x = DeploymentSpec{}
	mi := &file_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSpec) ProtoMessage() {}

func (x *DeploymentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSpec.ProtoReflect.Descriptor instead.
func (*DeploymentSpec) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentSpec) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeploymentSpec) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *DeploymentSpec) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *DeploymentSpec) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeploymentSpec) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DeploymentSpec) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *DeploymentSpec) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *DeploymentSpec) GetResources() *ResourceLimits {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DeploymentSpec) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryMb      int64                  `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"` // Memory limit in MB
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"` // CPU cores (1 = 1 core)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceLimits) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *DeploymentSpec        `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *DeployRequest) GetSpec() *DeploymentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                        // "running", "pending", "failed"
	PublicUrl     string                 `protobuf:"bytes,4,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"` // The accessible URL
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *DeployResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DeployResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeployResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *DeployResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDeploymentRequest) Reset() {
	*x = StopDeploymentRequest{}
	mi := &file_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDeploymentRequest) ProtoMessage() {}

func (x *StopDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDeploymentRequest.ProtoReflect.Descriptor instead.
func (*StopDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *StopDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *StopDeploymentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type StopDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDeploymentResponse) Reset() {
	*x = StopDeploymentResponse{}
	mi := &file_deployment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDeploymentResponse) ProtoMessage() {}

func (x *StopDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDeploymentResponse.ProtoReflect.Descriptor instead.
func (*StopDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *StopDeploymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopDeploymentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDeploymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusRequest) Reset() {
	*x = GetDeploymentStatusRequest{}
	mi := &file_deployment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusRequest) ProtoMessage() {}

func (x *GetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeploymentStatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *GetDeploymentStatusRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetDeploymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status        DeploymentStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=deployment.DeploymentStatus" json:"status,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,4,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusResponse) Reset() {
	*x = GetDeploymentStatusResponse{}
	mi := &file_deployment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusResponse) ProtoMessage() {}

func (x *GetDeploymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeploymentStatusResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetStatus() DeploymentStatus {
	if x != nil {
		return x.Status
	}
	return DeploymentStatus_DEPLOYMENT_STATUS_UNSPECIFIED
}

func (x *GetDeploymentStatusResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RestartDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDeploymentRequest) Reset() {
	*x = RestartDeploymentRequest{}
	mi := &file_deployment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDeploymentRequest) ProtoMessage() {}

func (x *RestartDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartDeploymentRequest.ProtoReflect.Descriptor instead.
func (*RestartDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{8}
}

func (x *RestartDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RestartDeploymentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type RestartDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDeploymentResponse) Reset() {
	*x = RestartDeploymentResponse{}
	mi := &file_deployment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDeploymentResponse) ProtoMessage() {}

func (x *RestartDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartDeploymentResponse.ProtoReflect.Descriptor instead.
func (*RestartDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{9}
}

func (x *RestartDeploymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestartDeploymentResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RestartDeploymentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRuntimeLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TailLines     int32                  `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"` // Number of lines to return (0 = all)
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`                        // Stream logs (not implemented in unary)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeLogsRequest) Reset() {
	*x = GetRuntimeLogsRequest{}
	mi := &file_deployment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeLogsRequest) ProtoMessage() {}

func (x *GetRuntimeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeLogsRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeLogsRequest) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{10}
}

func (x *GetRuntimeLogsRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *GetRuntimeLogsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetRuntimeLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *GetRuntimeLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type GetRuntimeLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogLines      []string               `protobuf:"bytes,1,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeLogsResponse) Reset() {
	*x = GetRuntimeLogsResponse{}
	mi := &file_deployment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeLogsResponse) ProtoMessage() {}

func (x *GetRuntimeLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeLogsResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeLogsResponse) Descriptor() ([]byte, []int) {
	return file_deployment_proto_rawDescGZIP(), []int{11}
}

func (x *GetRuntimeLogsResponse) GetLogLines() []string {
	if x != nil {
		return x.LogLines
	}
	return nil
}

func (x *GetRuntimeLogsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_deployment_proto protoreflect.FileDescriptor

const file_deployment_proto_rawDesc = "" +
	"\n" +
	"\x10deployment.proto\x12\n" +
	"deployment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x03\n" +
	"\x0eDeploymentSpec\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12\x1b\n" +
	"\timage_tag\x18\x03 \x01(\tR\bimageTag\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12B\n" +
	"\benv_vars\x18\x06 \x03(\v2'.deployment.DeploymentSpec.EnvVarsEntryR\aenvVars\x12A\n" +
	"\asecrets\x18\a \x03(\v2'.deployment.DeploymentSpec.SecretsEntryR\asecrets\x128\n" +
	"\tresources\x18\b \x01(\v2\x1a.deployment.ResourceLimitsR\tresources\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tmemory_mb\x18\x01 \x01(\x03R\bmemoryMb\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\"?\n" +
	"\rDeployRequest\x12.\n" +
	"\x04spec\x18\x01 \x01(\v2\x1a.deployment.DeploymentSpecR\x04spec\"\xa5\x01\n" +
	"\x0eDeployResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"public_url\x18\x04 \x01(\tR\tpublicUrl\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"[\n" +
	"\x15StopDeploymentRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"H\n" +
	"\x16StopDeploymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"`\n" +
	"\x1aGetDeploymentStatusRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\x8b\x02\n" +
	"\x1bGetDeploymentStatusResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.deployment.DeploymentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"public_url\x18\x04 \x01(\tR\tpublicUrl\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"^\n" +
	"\x18RestartDeploymentRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"n\n" +
	"\x19RestartDeploymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x92\x01\n" +
	"\x15GetRuntimeLogsRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\"K\n" +
	"\x16GetRuntimeLogsResponse\x12\x1b\n" +
	"\tlog_lines\x18\x01 \x03(\tR\blogLines\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\xd2\x01\n" +
	"\x10DeploymentStatus\x12!\n" +
	"\x1dDEPLOYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DEPLOYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19DEPLOYMENT_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19DEPLOYMENT_STATUS_STOPPED\x10\x03\x12\x1c\n" +
	"\x18DEPLOYMENT_STATUS_FAILED\x10\x04\x12 \n" +
	"\x1cDEPLOYMENT_STATUS_RESTARTING\x10\x052\xd0\x03\n" +
	"\x11DeploymentService\x12?\n" +
	"\x06Deploy\x12\x19.deployment.DeployRequest\x1a\x1a.deployment.DeployResponse\x12W\n" +
	"\x0eStopDeployment\x12!.deployment.StopDeploymentRequest\x1a\".deployment.StopDeploymentResponse\x12f\n" +
	"\x13GetDeploymentStatus\x12&.deployment.GetDeploymentStatusRequest\x1a'.deployment.GetDeploymentStatusResponse\x12`\n" +
	"\x11RestartDeployment\x12$.deployment.RestartDeploymentRequest\x1a%.deployment.RestartDeploymentResponse\x12W\n" +
	"\x0eGetRuntimeLogs\x12!.deployment.GetRuntimeLogsRequest\x1a\".deployment.GetRuntimeLogsResponseBBZ@github.com/nexusdeploy/backend/services/deployment-service/protob\x06proto3"

var (
	file_deployment_proto_rawDescOnce sync.Once
	file_deployment_proto_rawDescData []byte
)

func file_deployment_proto_rawDescGZIP() []byte {
	file_deployment_proto_rawDescOnce.Do(func() {
		file_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployment_proto_rawDesc), len(file_deployment_proto_rawDesc)))
	})
	return file_deployment_proto_rawDescData
}

var file_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_deployment_proto_goTypes = []any{
	(DeploymentStatus)(0),               // 0: deployment.DeploymentStatus
	(*DeploymentSpec)(nil),              // 1: deployment.DeploymentSpec
	(*ResourceLimits)(nil),              // 2: deployment.ResourceLimits
	(*DeployRequest)(nil),               // 3: deployment.DeployRequest
	(*DeployResponse)(nil),              // 4: deployment.DeployResponse
	(*StopDeploymentRequest)(nil),       // 5: deployment.StopDeploymentRequest
	(*StopDeploymentResponse)(nil),      // 6: deployment.StopDeploymentResponse
	(*GetDeploymentStatusRequest)(nil),  // 7: deployment.GetDeploymentStatusRequest
	(*GetDeploymentStatusResponse)(nil), // 8: deployment.GetDeploymentStatusResponse
	(*RestartDeploymentRequest)(nil),    // 9: deployment.RestartDeploymentRequest
	(*RestartDeploymentResponse)(nil),   // 10: deployment.RestartDeploymentResponse
	(*GetRuntimeLogsRequest)(nil),       // 11: deployment.GetRuntimeLogsRequest
	(*GetRuntimeLogsResponse)(nil),      // 12: deployment.GetRuntimeLogsResponse
	nil,                                 // 13: deployment.DeploymentSpec.EnvVarsEntry
	nil,                                 // 14: deployment.DeploymentSpec.SecretsEntry
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
}
var file_deployment_proto_depIdxs = []int32{
	13, // 0: deployment.DeploymentSpec.env_vars:type_name -> deployment.DeploymentSpec.EnvVarsEntry
	14, // 1: deployment.DeploymentSpec.secrets:type_name -> deployment.DeploymentSpec.SecretsEntry
	2,  // 2: deployment.DeploymentSpec.resources:type_name -> deployment.ResourceLimits
	1,  // 3: deployment.DeployRequest.spec:type_name -> deployment.DeploymentSpec
	0,  // 4: deployment.GetDeploymentStatusResponse.status:type_name -> deployment.DeploymentStatus
	15, // 5: deployment.GetDeploymentStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	3,  // 6: deployment.DeploymentService.Deploy:input_type -> deployment.DeployRequest
	5,  // 7: deployment.DeploymentService.StopDeployment:input_type -> deployment.StopDeploymentRequest
	7,  // 8: deployment.DeploymentService.GetDeploymentStatus:input_type -> deployment.GetDeploymentStatusRequest
	9,  // 9: deployment.DeploymentService.RestartDeployment:input_type -> deployment.RestartDeploymentRequest
	11, // 10: deployment.DeploymentService.GetRuntimeLogs:input_type -> deployment.GetRuntimeLogsRequest
	4,  // 11: deployment.DeploymentService.Deploy:output_type -> deployment.DeployResponse
	6,  // 12: deployment.DeploymentService.StopDeployment:output_type -> deployment.StopDeploymentResponse
	8,  // 13: deployment.DeploymentService.GetDeploymentStatus:output_type -> deployment.GetDeploymentStatusResponse
	10, // 14: deployment.DeploymentService.RestartDeployment:output_type -> deployment.RestartDeploymentResponse
	12, // 15: deployment.DeploymentService.GetRuntimeLogs:output_type -> deployment.GetRuntimeLogsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_deployment_proto_init() }
func file_deployment_proto_init() {
	if File_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployment_proto_rawDesc), len(file_deployment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployment_proto_goTypes,
		DependencyIndexes: file_deployment_proto_depIdxs,
		EnumInfos:         file_deployment_proto_enumTypes,
		MessageInfos:      file_deployment_proto_msgTypes,
	}.Build()
	File_deployment_proto = out.File
	file_deployment_proto_goTypes = nil
	file_deployment_proto_depIdxs = nil
}
