// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ai.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- AnalyzeBuild ---
type AnalyzeBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	UserPlan      string                 `protobuf:"bytes,2,opt,name=user_plan,json=userPlan,proto3" json:"user_plan,omitempty"` // "standard" or "premium"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBuildRequest) Reset() {
	*x = AnalyzeBuildRequest{}
	mi := &file_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBuildRequest) ProtoMessage() {}

func (x *AnalyzeBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBuildRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *AnalyzeBuildRequest) GetUserPlan() string {
	if x != nil {
		return x.UserPlan
	}
	return ""
}

type AnalyzeBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      string                 `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`       // Detailed analysis of the error
	Suggestions   []string               `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"` // Actionable suggestions to fix the error
	Cached        bool                   `protobuf:"varint,3,opt,name=cached,proto3" json:"cached,omitempty"`          // Whether the result was from cache
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`             // Error message if analysis failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBuildResponse) Reset() {
	*x = AnalyzeBuildResponse{}
	mi := &file_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBuildResponse) ProtoMessage() {}

func (x *AnalyzeBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBuildResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeBuildResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeBuildResponse) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *AnalyzeBuildResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AnalyzeBuildResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *AnalyzeBuildResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_ai_proto protoreflect.FileDescriptor

const file_proto_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ai.proto\x12\x02ai\"M\n" +
	"\x13AnalyzeBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x1b\n" +
	"\tuser_plan\x18\x02 \x01(\tR\buserPlan\"\x82\x01\n" +
	"\x14AnalyzeBuildResponse\x12\x1a\n" +
	"\banalysis\x18\x01 \x01(\tR\banalysis\x12 \n" +
	"\vsuggestions\x18\x02 \x03(\tR\vsuggestions\x12\x16\n" +
	"\x06cached\x18\x03 \x01(\bR\x06cached\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2N\n" +
	"\tAIService\x12A\n" +
	"\fAnalyzeBuild\x12\x17.ai.AnalyzeBuildRequest\x1a\x18.ai.AnalyzeBuildResponseB:Z8github.com/nexusdeploy/backend/services/ai-service/protob\x06proto3"

var (
	file_proto_ai_proto_rawDescOnce sync.Once
	file_proto_ai_proto_rawDescData []byte
)

func file_proto_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)))
	})
	return file_proto_ai_proto_rawDescData
}

var file_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ai_proto_goTypes = []any{
	(*AnalyzeBuildRequest)(nil),  // 0: ai.AnalyzeBuildRequest
	(*AnalyzeBuildResponse)(nil), // 1: ai.AnalyzeBuildResponse
}
var file_proto_ai_proto_depIdxs = []int32{
	0, // 0: ai.AIService.AnalyzeBuild:input_type -> ai.AnalyzeBuildRequest
	1, // 1: ai.AIService.AnalyzeBuild:output_type -> ai.AnalyzeBuildResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_proto_init() }
func file_proto_ai_proto_init() {
	if File_proto_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_proto = out.File
	file_proto_ai_proto_goTypes = nil
	file_proto_ai_proto_depIdxs = nil
}
