// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/build.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildService_TriggerBuild_FullMethodName      = "/build.BuildService/TriggerBuild"
	BuildService_UpdateBuildStatus_FullMethodName = "/build.BuildService/UpdateBuildStatus"
	BuildService_ListBuilds_FullMethodName        = "/build.BuildService/ListBuilds"
	BuildService_GetBuild_FullMethodName          = "/build.BuildService/GetBuild"
	BuildService_GetBuildLogs_FullMethodName      = "/build.BuildService/GetBuildLogs"
	BuildService_AppendBuildLogs_FullMethodName   = "/build.BuildService/AppendBuildLogs"
	BuildService_DeleteBuildLogs_FullMethodName   = "/build.BuildService/DeleteBuildLogs"
)

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Build Service - CI/CD Pipeline Orchestrator
type BuildServiceClient interface {
	// Trigger a new build (called by API Gateway when webhook received)
	TriggerBuild(ctx context.Context, in *TriggerBuildRequest, opts ...grpc.CallOption) (*TriggerBuildResponse, error)
	// Update build status (called by Runner Service)
	UpdateBuildStatus(ctx context.Context, in *UpdateBuildStatusRequest, opts ...grpc.CallOption) (*UpdateBuildStatusResponse, error)
	// List builds for a project (called by API Gateway)
	ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error)
	// Get build details (called by API Gateway, AI Service)
	GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error)
	// Get build logs (called by AI Service for error analysis)
	GetBuildLogs(ctx context.Context, in *GetBuildLogsRequest, opts ...grpc.CallOption) (*GetBuildLogsResponse, error)
	// Append logs to a build (called by Runner Service)
	AppendBuildLogs(ctx context.Context, in *AppendBuildLogsRequest, opts ...grpc.CallOption) (*AppendBuildLogsResponse, error)
	// Delete logs for builds in a project (called by API Gateway)
	DeleteBuildLogs(ctx context.Context, in *DeleteBuildLogsRequest, opts ...grpc.CallOption) (*DeleteBuildLogsResponse, error)
}

type buildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildServiceClient(cc grpc.ClientConnInterface) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) TriggerBuild(ctx context.Context, in *TriggerBuildRequest, opts ...grpc.CallOption) (*TriggerBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerBuildResponse)
	err := c.cc.Invoke(ctx, BuildService_TriggerBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) UpdateBuildStatus(ctx context.Context, in *UpdateBuildStatusRequest, opts ...grpc.CallOption) (*UpdateBuildStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBuildStatusResponse)
	err := c.cc.Invoke(ctx, BuildService_UpdateBuildStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) ListBuilds(ctx context.Context, in *ListBuildsRequest, opts ...grpc.CallOption) (*ListBuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuildsResponse)
	err := c.cc.Invoke(ctx, BuildService_ListBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildResponse)
	err := c.cc.Invoke(ctx, BuildService_GetBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) GetBuildLogs(ctx context.Context, in *GetBuildLogsRequest, opts ...grpc.CallOption) (*GetBuildLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildLogsResponse)
	err := c.cc.Invoke(ctx, BuildService_GetBuildLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) AppendBuildLogs(ctx context.Context, in *AppendBuildLogsRequest, opts ...grpc.CallOption) (*AppendBuildLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendBuildLogsResponse)
	err := c.cc.Invoke(ctx, BuildService_AppendBuildLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) DeleteBuildLogs(ctx context.Context, in *DeleteBuildLogsRequest, opts ...grpc.CallOption) (*DeleteBuildLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBuildLogsResponse)
	err := c.cc.Invoke(ctx, BuildService_DeleteBuildLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
// All implementations must embed UnimplementedBuildServiceServer
// for forward compatibility.
//
// Build Service - CI/CD Pipeline Orchestrator
type BuildServiceServer interface {
	// Trigger a new build (called by API Gateway when webhook received)
	TriggerBuild(context.Context, *TriggerBuildRequest) (*TriggerBuildResponse, error)
	// Update build status (called by Runner Service)
	UpdateBuildStatus(context.Context, *UpdateBuildStatusRequest) (*UpdateBuildStatusResponse, error)
	// List builds for a project (called by API Gateway)
	ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error)
	// Get build details (called by API Gateway, AI Service)
	GetBuild(context.Context, *GetBuildRequest) (*GetBuildResponse, error)
	// Get build logs (called by AI Service for error analysis)
	GetBuildLogs(context.Context, *GetBuildLogsRequest) (*GetBuildLogsResponse, error)
	// Append logs to a build (called by Runner Service)
	AppendBuildLogs(context.Context, *AppendBuildLogsRequest) (*AppendBuildLogsResponse, error)
	// Delete logs for builds in a project (called by API Gateway)
	DeleteBuildLogs(context.Context, *DeleteBuildLogsRequest) (*DeleteBuildLogsResponse, error)
	mustEmbedUnimplementedBuildServiceServer()
}

// UnimplementedBuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildServiceServer struct{}

func (UnimplementedBuildServiceServer) TriggerBuild(context.Context, *TriggerBuildRequest) (*TriggerBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerBuild not implemented")
}
func (UnimplementedBuildServiceServer) UpdateBuildStatus(context.Context, *UpdateBuildStatusRequest) (*UpdateBuildStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBuildStatus not implemented")
}
func (UnimplementedBuildServiceServer) ListBuilds(context.Context, *ListBuildsRequest) (*ListBuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuilds not implemented")
}
func (UnimplementedBuildServiceServer) GetBuild(context.Context, *GetBuildRequest) (*GetBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuild not implemented")
}
func (UnimplementedBuildServiceServer) GetBuildLogs(context.Context, *GetBuildLogsRequest) (*GetBuildLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuildLogs not implemented")
}
func (UnimplementedBuildServiceServer) AppendBuildLogs(context.Context, *AppendBuildLogsRequest) (*AppendBuildLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendBuildLogs not implemented")
}
func (UnimplementedBuildServiceServer) DeleteBuildLogs(context.Context, *DeleteBuildLogsRequest) (*DeleteBuildLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBuildLogs not implemented")
}
func (UnimplementedBuildServiceServer) mustEmbedUnimplementedBuildServiceServer() {}
func (UnimplementedBuildServiceServer) testEmbeddedByValue()                      {}

// UnsafeBuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildServiceServer will
// result in compilation errors.
type UnsafeBuildServiceServer interface {
	mustEmbedUnimplementedBuildServiceServer()
}

func RegisterBuildServiceServer(s grpc.ServiceRegistrar, srv BuildServiceServer) {
	// If the following call panics, it indicates UnimplementedBuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildService_ServiceDesc, srv)
}

func _BuildService_TriggerBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).TriggerBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_TriggerBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).TriggerBuild(ctx, req.(*TriggerBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_UpdateBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBuildStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).UpdateBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_UpdateBuildStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).UpdateBuildStatus(ctx, req.(*UpdateBuildStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_ListBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).ListBuilds(ctx, req.(*ListBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_GetBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).GetBuild(ctx, req.(*GetBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_GetBuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).GetBuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_GetBuildLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).GetBuildLogs(ctx, req.(*GetBuildLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_AppendBuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendBuildLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).AppendBuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_AppendBuildLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).AppendBuildLogs(ctx, req.(*AppendBuildLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_DeleteBuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBuildLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).DeleteBuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_DeleteBuildLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).DeleteBuildLogs(ctx, req.(*DeleteBuildLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildService_ServiceDesc is the grpc.ServiceDesc for BuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "build.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerBuild",
			Handler:    _BuildService_TriggerBuild_Handler,
		},
		{
			MethodName: "UpdateBuildStatus",
			Handler:    _BuildService_UpdateBuildStatus_Handler,
		},
		{
			MethodName: "ListBuilds",
			Handler:    _BuildService_ListBuilds_Handler,
		},
		{
			MethodName: "GetBuild",
			Handler:    _BuildService_GetBuild_Handler,
		},
		{
			MethodName: "GetBuildLogs",
			Handler:    _BuildService_GetBuildLogs_Handler,
		},
		{
			MethodName: "AppendBuildLogs",
			Handler:    _BuildService_AppendBuildLogs_Handler,
		},
		{
			MethodName: "DeleteBuildLogs",
			Handler:    _BuildService_DeleteBuildLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/build.proto",
}
