// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: build.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Build status enum matching state machine in SRS 3.4.1
type BuildStatus int32

const (
	BuildStatus_BUILD_STATUS_UNSPECIFIED    BuildStatus = 0
	BuildStatus_BUILD_STATUS_PENDING        BuildStatus = 1
	BuildStatus_BUILD_STATUS_RUNNING        BuildStatus = 2
	BuildStatus_BUILD_STATUS_FAILED         BuildStatus = 3
	BuildStatus_BUILD_STATUS_BUILDING_IMAGE BuildStatus = 4
	BuildStatus_BUILD_STATUS_PUSHING_IMAGE  BuildStatus = 5
	BuildStatus_BUILD_STATUS_DEPLOYING      BuildStatus = 6
	BuildStatus_BUILD_STATUS_SUCCESS        BuildStatus = 7
	BuildStatus_BUILD_STATUS_DEPLOY_FAILED  BuildStatus = 8
)

// Enum value maps for BuildStatus.
var (
	BuildStatus_name = map[int32]string{
		0: "BUILD_STATUS_UNSPECIFIED",
		1: "BUILD_STATUS_PENDING",
		2: "BUILD_STATUS_RUNNING",
		3: "BUILD_STATUS_FAILED",
		4: "BUILD_STATUS_BUILDING_IMAGE",
		5: "BUILD_STATUS_PUSHING_IMAGE",
		6: "BUILD_STATUS_DEPLOYING",
		7: "BUILD_STATUS_SUCCESS",
		8: "BUILD_STATUS_DEPLOY_FAILED",
	}
	BuildStatus_value = map[string]int32{
		"BUILD_STATUS_UNSPECIFIED":    0,
		"BUILD_STATUS_PENDING":        1,
		"BUILD_STATUS_RUNNING":        2,
		"BUILD_STATUS_FAILED":         3,
		"BUILD_STATUS_BUILDING_IMAGE": 4,
		"BUILD_STATUS_PUSHING_IMAGE":  5,
		"BUILD_STATUS_DEPLOYING":      6,
		"BUILD_STATUS_SUCCESS":        7,
		"BUILD_STATUS_DEPLOY_FAILED":  8,
	}
)

func (x BuildStatus) Enum() *BuildStatus {
	p := new(BuildStatus)
	*p = x
	return p
}

func (x BuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_build_proto_enumTypes[0].Descriptor()
}

func (BuildStatus) Type() protoreflect.EnumType {
	return &file_build_proto_enumTypes[0]
}

func (x BuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus.Descriptor instead.
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{0}
}

// Build message
type Build struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CommitSha     string                 `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Status        BuildStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=build.BuildStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{0}
}

func (x *Build) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Build) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Build) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Build) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BUILD_STATUS_UNSPECIFIED
}

func (x *Build) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Build) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Build) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Build) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// BuildStep message
type BuildStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	StepName      string                 `protobuf:"bytes,3,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStep) Reset() {
	*x = BuildStep{}
	mi := &file_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStep) ProtoMessage() {}

func (x *BuildStep) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStep.ProtoReflect.Descriptor instead.
func (*BuildStep) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{1}
}

func (x *BuildStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildStep) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildStep) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *BuildStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BuildStep) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// BuildLog message
type BuildLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogLine       string                 `protobuf:"bytes,4,opt,name=log_line,json=logLine,proto3" json:"log_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildLog) Reset() {
	*x = BuildLog{}
	mi := &file_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLog) ProtoMessage() {}

func (x *BuildLog) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLog.ProtoReflect.Descriptor instead.
func (*BuildLog) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{2}
}

func (x *BuildLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildLog) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BuildLog) GetLogLine() string {
	if x != nil {
		return x.LogLine
	}
	return ""
}

// --- TriggerBuild ---
type TriggerBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CommitSha     string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For permission check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildRequest) Reset() {
	*x = TriggerBuildRequest{}
	mi := &file_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildRequest) ProtoMessage() {}

func (x *TriggerBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildRequest.ProtoReflect.Descriptor instead.
func (*TriggerBuildRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerBuildRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TriggerBuildRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *TriggerBuildRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *TriggerBuildRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *TriggerBuildRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TriggerBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *Build                 `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildResponse) Reset() {
	*x = TriggerBuildResponse{}
	mi := &file_build_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildResponse) ProtoMessage() {}

func (x *TriggerBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildResponse.ProtoReflect.Descriptor instead.
func (*TriggerBuildResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *TriggerBuildResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- UpdateBuildStatus ---
type UpdateBuildStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Status        BuildStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=build.BuildStatus" json:"status,omitempty"`
	LogLines      []string               `protobuf:"bytes,3,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"` // Optional: append logs when updating
	ImageTag      string                 `protobuf:"bytes,4,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"` // Set when status is PUSHING_IMAGE or later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuildStatusRequest) Reset() {
	*x = UpdateBuildStatusRequest{}
	mi := &file_build_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildStatusRequest) ProtoMessage() {}

func (x *UpdateBuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBuildStatusRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *UpdateBuildStatusRequest) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BUILD_STATUS_UNSPECIFIED
}

func (x *UpdateBuildStatusRequest) GetLogLines() []string {
	if x != nil {
		return x.LogLines
	}
	return nil
}

func (x *UpdateBuildStatusRequest) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

type UpdateBuildStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuildStatusResponse) Reset() {
	*x = UpdateBuildStatusResponse{}
	mi := &file_build_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuildStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildStatusResponse) ProtoMessage() {}

func (x *UpdateBuildStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateBuildStatusResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBuildStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *UpdateBuildStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- ListBuilds ---
type ListBuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_build_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{7}
}

func (x *ListBuildsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListBuildsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListBuildsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBuildsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*Build               `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsResponse) Reset() {
	*x = ListBuildsResponse{}
	mi := &file_build_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsResponse) ProtoMessage() {}

func (x *ListBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{8}
}

func (x *ListBuildsResponse) GetBuilds() []*Build {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *ListBuildsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBuildsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- GetBuild ---
type GetBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For permission check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_build_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{9}
}

func (x *GetBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *GetBuildRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *Build                 `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	Steps         []*BuildStep           `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildResponse) Reset() {
	*x = GetBuildResponse{}
	mi := &file_build_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildResponse) ProtoMessage() {}

func (x *GetBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildResponse.ProtoReflect.Descriptor instead.
func (*GetBuildResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{10}
}

func (x *GetBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *GetBuildResponse) GetSteps() []*BuildStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GetBuildResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- GetBuildLogs ---
type GetBuildLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                    // Max number of log lines to return
	AfterId       int64                  `protobuf:"varint,3,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"` // For pagination: return logs after this ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildLogsRequest) Reset() {
	*x = GetBuildLogsRequest{}
	mi := &file_build_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildLogsRequest) ProtoMessage() {}

func (x *GetBuildLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildLogsRequest.ProtoReflect.Descriptor instead.
func (*GetBuildLogsRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{11}
}

func (x *GetBuildLogsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *GetBuildLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetBuildLogsRequest) GetAfterId() int64 {
	if x != nil {
		return x.AfterId
	}
	return 0
}

type GetBuildLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*BuildLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildLogsResponse) Reset() {
	*x = GetBuildLogsResponse{}
	mi := &file_build_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildLogsResponse) ProtoMessage() {}

func (x *GetBuildLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildLogsResponse.ProtoReflect.Descriptor instead.
func (*GetBuildLogsResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{12}
}

func (x *GetBuildLogsResponse) GetLogs() []*BuildLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetBuildLogsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetBuildLogsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- AppendBuildLogs ---
type AppendBuildLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	LogLines      []string               `protobuf:"bytes,2,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBuildLogsRequest) Reset() {
	*x = AppendBuildLogsRequest{}
	mi := &file_build_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBuildLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBuildLogsRequest) ProtoMessage() {}

func (x *AppendBuildLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBuildLogsRequest.ProtoReflect.Descriptor instead.
func (*AppendBuildLogsRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{13}
}

func (x *AppendBuildLogsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *AppendBuildLogsRequest) GetLogLines() []string {
	if x != nil {
		return x.LogLines
	}
	return nil
}

type AppendBuildLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBuildLogsResponse) Reset() {
	*x = AppendBuildLogsResponse{}
	mi := &file_build_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBuildLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBuildLogsResponse) ProtoMessage() {}

func (x *AppendBuildLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBuildLogsResponse.ProtoReflect.Descriptor instead.
func (*AppendBuildLogsResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{14}
}

func (x *AppendBuildLogsResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *AppendBuildLogsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- DeleteBuildLogs ---
type DeleteBuildLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // For permission check
	BuildIds      []string               `protobuf:"bytes,3,rep,name=build_ids,json=buildIds,proto3" json:"build_ids,omitempty"` // Optional: specific build IDs, if empty delete all for project
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildLogsRequest) Reset() {
	*x = DeleteBuildLogsRequest{}
	mi := &file_build_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildLogsRequest) ProtoMessage() {}

func (x *DeleteBuildLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildLogsRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuildLogsRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteBuildLogsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteBuildLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteBuildLogsRequest) GetBuildIds() []string {
	if x != nil {
		return x.BuildIds
	}
	return nil
}

type DeleteBuildLogsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BuildsAffected int32                  `protobuf:"varint,1,opt,name=builds_affected,json=buildsAffected,proto3" json:"builds_affected,omitempty"`
	LogsDeleted    int64                  `protobuf:"varint,2,opt,name=logs_deleted,json=logsDeleted,proto3" json:"logs_deleted,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteBuildLogsResponse) Reset() {
	*x = DeleteBuildLogsResponse{}
	mi := &file_build_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildLogsResponse) ProtoMessage() {}

func (x *DeleteBuildLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildLogsResponse.ProtoReflect.Descriptor instead.
func (*DeleteBuildLogsResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteBuildLogsResponse) GetBuildsAffected() int32 {
	if x != nil {
		return x.BuildsAffected
	}
	return 0
}

func (x *DeleteBuildLogsResponse) GetLogsDeleted() int64 {
	if x != nil {
		return x.LogsDeleted
	}
	return 0
}

func (x *DeleteBuildLogsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_build_proto protoreflect.FileDescriptor

const file_build_proto_rawDesc = "" +
	"\n" +
	"\vbuild.proto\x12\x05build\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x02\n" +
	"\x05Build\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.build.BuildStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x01\n" +
	"\tBuildStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12\x1b\n" +
	"\tstep_name\x18\x03 \x01(\tR\bstepName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\"\x8a\x01\n" +
	"\bBuildLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\blog_line\x18\x04 \x01(\tR\alogLine\"\x9f\x01\n" +
	"\x13TriggerBuildRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"P\n" +
	"\x14TriggerBuildResponse\x12\"\n" +
	"\x05build\x18\x01 \x01(\v2\f.build.BuildR\x05build\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9b\x01\n" +
	"\x18UpdateBuildStatusRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.build.BuildStatusR\x06status\x12\x1b\n" +
	"\tlog_lines\x18\x03 \x03(\tR\blogLines\x12\x1b\n" +
	"\timage_tag\x18\x04 \x01(\tR\bimageTag\"U\n" +
	"\x19UpdateBuildStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"|\n" +
	"\x11ListBuildsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"f\n" +
	"\x12ListBuildsResponse\x12$\n" +
	"\x06builds\x18\x01 \x03(\v2\f.build.BuildR\x06builds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"E\n" +
	"\x0fGetBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"t\n" +
	"\x10GetBuildResponse\x12\"\n" +
	"\x05build\x18\x01 \x01(\v2\f.build.BuildR\x05build\x12&\n" +
	"\x05steps\x18\x02 \x03(\v2\x10.build.BuildStepR\x05steps\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"a\n" +
	"\x13GetBuildLogsRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\bafter_id\x18\x03 \x01(\x03R\aafterId\"l\n" +
	"\x14GetBuildLogsResponse\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.build.BuildLogR\x04logs\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"P\n" +
	"\x16AppendBuildLogsRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x1b\n" +
	"\tlog_lines\x18\x02 \x03(\tR\blogLines\"S\n" +
	"\x17AppendBuildLogsResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"m\n" +
	"\x16DeleteBuildLogsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbuild_ids\x18\x03 \x03(\tR\bbuildIds\"{\n" +
	"\x17DeleteBuildLogsResponse\x12'\n" +
	"\x0fbuilds_affected\x18\x01 \x01(\x05R\x0ebuildsAffected\x12!\n" +
	"\flogs_deleted\x18\x02 \x01(\x03R\vlogsDeleted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\x8f\x02\n" +
	"\vBuildStatus\x12\x1c\n" +
	"\x18BUILD_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BUILD_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14BUILD_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13BUILD_STATUS_FAILED\x10\x03\x12\x1f\n" +
	"\x1bBUILD_STATUS_BUILDING_IMAGE\x10\x04\x12\x1e\n" +
	"\x1aBUILD_STATUS_PUSHING_IMAGE\x10\x05\x12\x1a\n" +
	"\x16BUILD_STATUS_DEPLOYING\x10\x06\x12\x18\n" +
	"\x14BUILD_STATUS_SUCCESS\x10\a\x12\x1e\n" +
	"\x1aBUILD_STATUS_DEPLOY_FAILED\x10\b2\x9c\x04\n" +
	"\fBuildService\x12G\n" +
	"\fTriggerBuild\x12\x1a.build.TriggerBuildRequest\x1a\x1b.build.TriggerBuildResponse\x12V\n" +
	"\x11UpdateBuildStatus\x12\x1f.build.UpdateBuildStatusRequest\x1a .build.UpdateBuildStatusResponse\x12A\n" +
	"\n" +
	"ListBuilds\x12\x18.build.ListBuildsRequest\x1a\x19.build.ListBuildsResponse\x12;\n" +
	"\bGetBuild\x12\x16.build.GetBuildRequest\x1a\x17.build.GetBuildResponse\x12G\n" +
	"\fGetBuildLogs\x12\x1a.build.GetBuildLogsRequest\x1a\x1b.build.GetBuildLogsResponse\x12P\n" +
	"\x0fAppendBuildLogs\x12\x1d.build.AppendBuildLogsRequest\x1a\x1e.build.AppendBuildLogsResponse\x12P\n" +
	"\x0fDeleteBuildLogs\x12\x1d.build.DeleteBuildLogsRequest\x1a\x1e.build.DeleteBuildLogsResponseB=Z;github.com/nexusdeploy/backend/services/build-service/protob\x06proto3"

var (
	file_build_proto_rawDescOnce sync.Once
	file_build_proto_rawDescData []byte
)

func file_build_proto_rawDescGZIP() []byte {
	file_build_proto_rawDescOnce.Do(func() {
		file_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_build_proto_rawDesc), len(file_build_proto_rawDesc)))
	})
	return file_build_proto_rawDescData
}

var file_build_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_build_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_build_proto_goTypes = []any{
	(BuildStatus)(0),                  // 0: build.BuildStatus
	(*Build)(nil),                     // 1: build.Build
	(*BuildStep)(nil),                 // 2: build.BuildStep
	(*BuildLog)(nil),                  // 3: build.BuildLog
	(*TriggerBuildRequest)(nil),       // 4: build.TriggerBuildRequest
	(*TriggerBuildResponse)(nil),      // 5: build.TriggerBuildResponse
	(*UpdateBuildStatusRequest)(nil),  // 6: build.UpdateBuildStatusRequest
	(*UpdateBuildStatusResponse)(nil), // 7: build.UpdateBuildStatusResponse
	(*ListBuildsRequest)(nil),         // 8: build.ListBuildsRequest
	(*ListBuildsResponse)(nil),        // 9: build.ListBuildsResponse
	(*GetBuildRequest)(nil),           // 10: build.GetBuildRequest
	(*GetBuildResponse)(nil),          // 11: build.GetBuildResponse
	(*GetBuildLogsRequest)(nil),       // 12: build.GetBuildLogsRequest
	(*GetBuildLogsResponse)(nil),      // 13: build.GetBuildLogsResponse
	(*AppendBuildLogsRequest)(nil),    // 14: build.AppendBuildLogsRequest
	(*AppendBuildLogsResponse)(nil),   // 15: build.AppendBuildLogsResponse
	(*DeleteBuildLogsRequest)(nil),    // 16: build.DeleteBuildLogsRequest
	(*DeleteBuildLogsResponse)(nil),   // 17: build.DeleteBuildLogsResponse
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
}
var file_build_proto_depIdxs = []int32{
	0,  // 0: build.Build.status:type_name -> build.BuildStatus
	18, // 1: build.Build.started_at:type_name -> google.protobuf.Timestamp
	18, // 2: build.Build.finished_at:type_name -> google.protobuf.Timestamp
	18, // 3: build.Build.created_at:type_name -> google.protobuf.Timestamp
	18, // 4: build.Build.updated_at:type_name -> google.protobuf.Timestamp
	18, // 5: build.BuildLog.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 6: build.TriggerBuildResponse.build:type_name -> build.Build
	0,  // 7: build.UpdateBuildStatusRequest.status:type_name -> build.BuildStatus
	1,  // 8: build.ListBuildsResponse.builds:type_name -> build.Build
	1,  // 9: build.GetBuildResponse.build:type_name -> build.Build
	2,  // 10: build.GetBuildResponse.steps:type_name -> build.BuildStep
	3,  // 11: build.GetBuildLogsResponse.logs:type_name -> build.BuildLog
	4,  // 12: build.BuildService.TriggerBuild:input_type -> build.TriggerBuildRequest
	6,  // 13: build.BuildService.UpdateBuildStatus:input_type -> build.UpdateBuildStatusRequest
	8,  // 14: build.BuildService.ListBuilds:input_type -> build.ListBuildsRequest
	10, // 15: build.BuildService.GetBuild:input_type -> build.GetBuildRequest
	12, // 16: build.BuildService.GetBuildLogs:input_type -> build.GetBuildLogsRequest
	14, // 17: build.BuildService.AppendBuildLogs:input_type -> build.AppendBuildLogsRequest
	16, // 18: build.BuildService.DeleteBuildLogs:input_type -> build.DeleteBuildLogsRequest
	5,  // 19: build.BuildService.TriggerBuild:output_type -> build.TriggerBuildResponse
	7,  // 20: build.BuildService.UpdateBuildStatus:output_type -> build.UpdateBuildStatusResponse
	9,  // 21: build.BuildService.ListBuilds:output_type -> build.ListBuildsResponse
	11, // 22: build.BuildService.GetBuild:output_type -> build.GetBuildResponse
	13, // 23: build.BuildService.GetBuildLogs:output_type -> build.GetBuildLogsResponse
	15, // 24: build.BuildService.AppendBuildLogs:output_type -> build.AppendBuildLogsResponse
	17, // 25: build.BuildService.DeleteBuildLogs:output_type -> build.DeleteBuildLogsResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_build_proto_init() }
func file_build_proto_init() {
	if File_build_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_build_proto_rawDesc), len(file_build_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_build_proto_goTypes,
		DependencyIndexes: file_build_proto_depIdxs,
		EnumInfos:         file_build_proto_enumTypes,
		MessageInfos:      file_build_proto_msgTypes,
	}.Build()
	File_build_proto = out.File
	file_build_proto_goTypes = nil
	file_build_proto_depIdxs = nil
}
